<?php
$z[0]=Array("field","",11,37);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",49,75);
$z[1][4]['name']="currentstyle";
$z[2]=Array("field","",83,111);
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",145,168);
$z[3][4]['name']="id";
$z[4]=Array("field","",197,226);
$z[4][4]['name']="typename";
$z[5]=Array("sql","\r\n            <li><a currentstyle='on' href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n          ",258,445);
$z[5][4]['sql']="Select * from `dede_arctype` where reid=~id~ ORDER BY id";

?>