<?php
$z[0]=Array("field","",11,37);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",49,75);
$z[1][4]['name']="currentstyle";
$z[2]=Array("field","",83,111);
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",145,168);
$z[3][4]['name']="id";
$z[4]=Array("field","",197,226);
$z[4][4]['name']="typename";
$z[5]=Array("channel","\r\n            <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n          ",258,473);
$z[5][4]['type']="son";
$z[5][4]['noself']="yes";
$z[5][4]['currentstyle']="<li><a class='on' href='~typelink~' ~rel~>~typename~</a></li>";

?>