<?php
$z[0]=Array("field","",11,37);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",48,76);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",110,133);
$z[2][4]['name']="id";
$z[3]=Array("field","",162,191);
$z[3][4]['name']="typename";
$z[4]=Array("sql","\r\n            <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n          ",223,392);
$z[4][4]['sql']="Select * from `dede_arctype` where reid=~id~ ORDER BY id";

?>