<?php
$z[0]=Array("field","",15,41);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",49,77);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",111,134);
$z[2][4]['name']="id";
$z[3]=Array("field","",163,192);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n            <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n          ",224,435);
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";
$z[4][4]['currentstyle']="<li><a class='on' href='~typelink~' >~typename~</a> </li>";

?>