<?php
$z[0]=Array("field","",25,51);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",59,87);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",121,144);
$z[2][4]['name']="id";
$z[3]=Array("field","",173,202);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n            <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n          ",234,447);
$z[4][4]['type']="7";
$z[4][4]['currentstyle']="<li><a class='on' href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>