<?php
$z[0]=Array("field","(@me==\"\")? @me=\" class='on'\":@me=\"\";",4,90);
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[1]=Array("field","",101,127);
$z[1][4]['name']="currentstyle";
$z[2]=Array("field","",135,163);
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",197,220);
$z[3][4]['name']="id";
$z[4]=Array("field","",249,278);
$z[4][4]['name']="typename";
$z[5]=Array("channel","\r\n            <li><a href=\"[field:typelink/]\" >[field:typename/]</a></li>\r\n          ",310,521);
$z[5][4]['type']="son";
$z[5][4]['channel']="17";
$z[5][4]['currentstyle']="<li><a class='on' href='~typelink~' >~typename~</a> </li>";

?>