<?php
$z[0]=Array("field","",11,37);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",48,76);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",110,133);
$z[2][4]['name']="id";
$z[3]=Array("field","",162,191);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n            <li><a href=\"[field:typeurl/]\" >[field:typename/]</a></li>\r\n          ",223,360);
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>