<?php
$z[0]=Array("channelartlist","\r\n    <li>\r\n      <div class=\"title\">{dede:field name='typename'/}</div>\r\n      {dede:channel type='son' noself='yes' }\r\n		<a href=\"[field:typelink/]\" target=\"_blank\" title=\"\">[field:typename/]</a>\r\n      {/dede:channel}\r\n	</li>\r\n  ",65,361);
$z[0][4]['typeid']="top";
$z[0][4]['row']="6";
$z[1]=Array("global","",1114,1140);
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",1152,1176);
$z[2][4]['name']="cfg_beian";

?>